FORMAT 1.0.0

# The Square API

The Square API allows you to authenticate and manage streams

# Group Authentication

All endpoints related to authentication. In all requests but `/v1/register`, it is required to send a `X-PublicKey` header, containing the users's public key that 
